apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: scp_test
    user: scp_test
    secureJsonData:
      password: scp_test_password
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    editable: false
