"""Signal object for RuleEngine trade signals.

This module defines the core Signal dataclass that represents a structured,
auditable trade signal adhering to Shir Capital's SOP requirements.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


@dataclass(frozen=True)
class Signal:
    """Structured trade signal with SOP-compliant scoring.

    Represents a complete trade signal generated by the RuleEngine,
    including setup classification, scoring breakdown, validation status,
    and human-readable rationale. Immutable to ensure auditability.

    Attributes:
        timestamp: Signal generation time (timezone-aware UTC datetime)
        symbol: Asset symbol (e.g., "GC", "DXY")
        timeframe: Candle period (e.g., "1m", "5m", "15m")
        direction: Trade direction ("long", "short", "neutral")
        setup_type: Setup classification (e.g., "VWAP_RECLAIM", "VWAP_FADE",
                   "DXY_CONTINUATION")
        htf_bias: Higher timeframe bias ("bullish", "bearish", "neutral")
        score: Numerical score (0-10) based on SOP factor weights
        confidence: Signal quality classification ("A+", "Watch", "Reject")
                   - A+: score >= 8 (tradeable)
                   - Watch: score 6-7 (monitor only)
                   - Reject: score < 6 (invalid)
        factors: Dict mapping factor names to their individual scores
                (e.g., {"structure_alignment": 2, "vwap_relation": 2})
        rationale: Human-readable explanation of the signal logic
        validation_flags: Dict of SOP compliance checks
                         (e.g., {"session_ok": True, "tier_ok": True})
        enforcer_tier: Active enforcer tier ("Conservative", "Early Mild",
                      "Mild", "Offensive")
        diagnostics: Optional dict with structure/setup diagnostics for debugging.
                    Contains raw values like structure_label, rsi, bos_age, etc.

    Example:
        >>> from datetime import datetime, timezone
        >>> signal = Signal(
        ...     timestamp=datetime(2025, 1, 1, 10, 0, tzinfo=timezone.utc),
        ...     symbol="GC",
        ...     timeframe="1m",
        ...     direction="long",
        ...     setup_type="VWAP_RECLAIM",
        ...     htf_bias="bullish",
        ...     score=9.0,
        ...     confidence="A+",
        ...     factors={"structure_alignment": 2, "vwap_relation": 2},
        ...     rationale="HTF HH/HL intact, VWAP reclaim confirmed",
        ...     validation_flags={"session_ok": True, "tier_ok": True},
        ...     enforcer_tier="Early Mild"
        ... )
    """

    timestamp: datetime
    symbol: str
    timeframe: str
    direction: str
    setup_type: str
    htf_bias: str
    score: float
    confidence: str
    factors: dict[str, float]
    rationale: str
    validation_flags: dict[str, bool]
    enforcer_tier: str
    # Optional diagnostics for debugging - contains structure params, RSI, BOS age, etc.
    diagnostics: dict[str, Any] = field(default_factory=dict)

